### ISSUE TITLE
TAS on PFD airspeed tape instead of IAS

### ISSUE THREAD

**Issue by BogdanPau** [tomvd/rtl1090xhsi#1]
Hi,

I'm using this software on Windows 10, plus the rtl1090 application to decode ADS-B broadcasts, plus the XHSI beta 12 alpha 5 in order to present the data on the cockpit instruments visually.
All seems to work pretty fine, beside the fact that for some reason this application sends to the XSHI TAS information instead of IAS for the PFD display on the airspeed tape.
I Googled a bit and found more people showing instructions how to use all applications and in their screenshots the same issue seems to happen.

I know this library is quite old and probably not maintained, I just thought to give it a try to ask for help about this issue and how it can be solved.

Thanks,
Bogdan

**Comment by tomvd** [comment]
Good find, I'm surprised people are actually using the software :)
Seems like an easy fix, replacing ADSB_TAS with ADSB_IAS where I send the data to the cockpit.

**Comment by BogdanPau** [comment]
Cool!
How can I commit that fix on the compiled rtl1090XHSI windows application I downloaded?

Thanks

**Comment by BogdanPau** [comment]
or in other words..
How can it be compiled so I can use the new exe version with this fix :)

**Comment by BogdanPau** [comment]
@tomvd Maybe you can help!
